# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ss.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ss.proto\x12\nhelloworld\"\x1f\n\x0cHelloRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1e\n\nHelloReply\x12\x10\n\x08response\x18\x01 \x01(\t2H\n\tssgreeter\x12;\n\x05sayOi\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ss_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=24
  _globals['_HELLOREQUEST']._serialized_end=55
  _globals['_HELLOREPLY']._serialized_start=57
  _globals['_HELLOREPLY']._serialized_end=87
  _globals['_SSGREETER']._serialized_start=89
  _globals['_SSGREETER']._serialized_end=161
# @@protoc_insertion_point(module_scope)
